# Generated by Django 4.2 on 2023-06-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('html', 'html'), ('css', 'css'), ('js', 'js'), ('python', 'python')], max_length=12)),
                ('assignment', models.FileField(upload_to='core/static/mediafiles')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=3000)),
                ('image', models.ImageField(default='core/static/mediafiles/css.png', upload_to='core/static/courses_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.FileField(blank=True, null=True, upload_to='core/static/courses_notes')),
            ],
            options={
                'verbose_name_plural': 'CSS',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='CSSComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Students CSS Comments',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=3000)),
                ('image', models.ImageField(default='core/static/mediafiles/html.png', upload_to='core/static/courses_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.FileField(blank=True, null=True, upload_to='core/static/courses_notes')),
            ],
            options={
                'verbose_name_plural': 'HTML',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='HTMLComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Students HTML Comments',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='JAVASCRIPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=3000)),
                ('image', models.ImageField(default='core/static/mediafiles/javascript.png', upload_to='core/static/courses_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.FileField(blank=True, null=True, upload_to='core/static/courses_notes')),
            ],
            options={
                'verbose_name_plural': 'JAVASCRIPT',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='JSComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Students JS Comments',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='PYTHON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=3000)),
                ('image', models.ImageField(default='core/static/mediafiles/python.png', upload_to='core/static/courses_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.FileField(blank=True, null=True, upload_to='core/static/courses_notes')),
            ],
            options={
                'verbose_name_plural': 'PYTHON',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='PythonComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Students Python Comments',
                'ordering': ('date',),
            },
        ),
    ]
